settings:
  # username: "Readme-Workflows" # Replace with your username or comment out this line
  commit_msg: 'Update activity'
  max_lines: 10
  # readme_file: "./TEMPLATE.md"
  disabled_events:
    - 'comments'
    - 'push'
  url_text: '{REPO}{ID}'
  date:
    timezone: 'Asia/Kuala_Lumpur'
    text: 'Activity updated: {DATE}'
    format: 'isoDateTime'
  # commit_name: "readme-bot"
  # commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
  line_prefix: '{NUM}. '
  ignored_repos:
    - HafiziRuslan/HafiziRuslan
messages:
  comments: 'ğŸ’¬ Commented on {ID} in {REPO}'
  push: 'â¬†ï¸ Pushed commit(s) to {REPO}'
  issue_opened: 'â—ï¸ Opened issue {ID} in {REPO}'
  issue_closed: 'âœ”ï¸ Closed issue {ID} in {REPO}'
  pr_opened: 'ğŸ’ª Opened PR {ID} in {REPO}'
  pr_closed: 'âŒ Closed PR {ID} in {REPO}'
  pr_merged: 'ğŸ‰ Merged PR {ID} in {REPO}'
  create_repo: 'ğŸ“” Created {REPO}'
  fork_repo: 'ğŸ”± Forked {FORK} from {REPO}'
  wiki_create: 'ğŸ“– Created new {WIKI} page in {REPO}'
  added_member: 'ğŸ¤ Became collaborator on {REPO}'
  changes_approved: 'ğŸ‘ Approved changes in {ID} in {REPO}'
  changes_requested: 'ğŸ”´ Requested changes in {ID} in {REPO}'
  new_release: 'âœŒï¸ Released {ID} in {REPO}'
  new_star: 'â­ Starred {REPO}'
