name: update

on:
  schedule:
    - cron: '0 0/2 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@main
      - name: Generate the user stats
        uses: cicirello/user-statistician@main
        with:
          include-title: true
          custom-title: ${{ github.repository_owner }}
          small-title: false
          featured-repository: 'RasPiAPRS'
          max-languages: auto
          animated-language-chart: true
          language-animation-speed: 20
          colors: dark-dimmed
          border-radius: 1
          show-border: false
          hide-keys: mostStarred, mostForked, followers, following, watchedBy
          commit-message: 'Update stats'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
